backend = "glx";
vsync = true;
use-damage = true;
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.25;
shadow-offset-x = -7;
shadow-offset-y = -7;
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
inactive-opacity = 1.0;
active-opacity = 1.0;
corner-radius = 0;

shadow-exclude = [
  "class_g = 'Dmenu'",
  "class_g = 'Rofi'",
  "name = 'Notification'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
